# The URL the site will be built for
base_url = "https://c.gelez.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "two-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# Put all your custom variables here
site_name = "Introduction au C"
icon = "/c.svg"
icon_desc = "Le logo du C"
description = "TODO"
default_illus = "/woodenc.webp"

primary_color = "#6A91D4"
accent_color = "#4DAA57"
